// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Needlr.Infrastructure.Persistence;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Needlr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NeedlrDbContext))]
    [Migration("20260506190750_AddStudioAcceptsWalkIns")]
    partial class AddStudioAcceptsWalkIns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Availability.ArtistAvailabilityProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsBookable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bookable");

                    b.Property<DateTime>("RecomputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recomputed_at");

                    b.Property<decimal>("RemainingSessionHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("remaining_session_hours");

                    b.HasKey("Id")
                        .HasName("pk_artist_availability_projections");

                    b.HasIndex("ArtistId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_artist_availability_projections_artist_id_date");

                    b.HasIndex("Date", "IsBookable")
                        .HasDatabaseName("ix_artist_availability_projections_date_is_bookable");

                    b.ToTable("artist_availability_projections", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Availability.AvailabilityOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal?>("MaxSessionHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_session_hours");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_availability_overrides");

                    b.HasIndex("ArtistId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_availability_overrides_artist_id_date");

                    b.ToTable("availability_overrides", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Availability.AvailabilityPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveUntil")
                        .HasColumnType("date")
                        .HasColumnName("effective_until");

                    b.Property<decimal?>("MaxSessionHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_session_hours");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_availability_patterns");

                    b.HasIndex("ArtistId", "EffectiveFrom")
                        .HasDatabaseName("ix_availability_patterns_artist_id_effective_from");

                    b.ToTable("availability_patterns", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Availability.BookingWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateOnly>("TargetRangeEnd")
                        .HasColumnType("date")
                        .HasColumnName("target_range_end");

                    b.Property<DateOnly>("TargetRangeStart")
                        .HasColumnType("date")
                        .HasColumnName("target_range_start");

                    b.Property<DateTime>("WindowClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_closes_at");

                    b.Property<DateTime>("WindowOpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_opens_at");

                    b.HasKey("Id")
                        .HasName("pk_booking_windows");

                    b.HasIndex("ArtistId", "WindowOpensAt", "WindowClosesAt")
                        .HasDatabaseName("ix_booking_windows_artist_id_window_opens_at_window_closes_at");

                    b.ToTable("booking_windows", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<int?>("ApproximateSizeCm")
                        .HasColumnType("integer")
                        .HasColumnName("approximate_size_cm");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("BodyPlacement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("body_placement");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("booking_type");

                    b.Property<string>("CancellationPolicySnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cancellation_policy_snapshot");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("ConfirmedSessionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_session_date");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeclineNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decline_note");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("decline_reason");

                    b.Property<decimal>("DepositAmountCad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("deposit_amount_cad");

                    b.Property<DateTime?>("DepositCapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deposit_captured_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<decimal>("EstimatedDurationHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_duration_hours");

                    b.Property<decimal?>("EstimatedTotalCad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_total_cad");

                    b.Property<DateTime?>("HealedPhotoPromptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("healed_photo_prompted_at");

                    b.Property<bool>("IsAttachmentsPurged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_attachments_purged");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_sent_at");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("date")
                        .HasColumnName("requested_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid")
                        .HasColumnName("studio_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("StudioId")
                        .HasDatabaseName("ix_bookings_studio_id");

                    b.HasIndex("ArtistId", "Status")
                        .HasDatabaseName("ix_bookings_artist_id_status");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("ix_bookings_customer_id_status");

                    b.HasIndex("IsAttachmentsPurged", "CompletedAt")
                        .HasDatabaseName("ix_bookings_is_attachments_purged_completed_at");

                    b.HasIndex("Status", "ConfirmedSessionDate")
                        .HasDatabaseName("ix_bookings_status_confirmed_session_date");

                    b.HasIndex("Status", "RequestedAt")
                        .HasDatabaseName("ix_bookings_status_requested_at");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Bookings.BookingAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_filename");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_booking_attachments");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_attachments_booking_id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_booking_attachments_message_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_booking_attachments_uploaded_by_user_id");

                    b.ToTable("booking_attachments", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Bookings.BookingFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("CleanlinessRating")
                        .HasColumnType("integer")
                        .HasColumnName("cleanliness_rating");

                    b.Property<int>("CommunicationRating")
                        .HasColumnType("integer")
                        .HasColumnName("communication_rating");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("FreeText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("free_text");

                    b.Property<int>("RespectedDesignBriefRating")
                        .HasColumnType("integer")
                        .HasColumnName("respected_design_brief_rating");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<bool>("WouldBookAgain")
                        .HasColumnType("boolean")
                        .HasColumnName("would_book_again");

                    b.HasKey("Id")
                        .HasName("pk_booking_feedbacks");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_feedbacks_booking_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_booking_feedbacks_customer_id");

                    b.ToTable("booking_feedbacks", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Identity.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AcceptingNewBookings")
                        .HasColumnType("boolean")
                        .HasColumnName("accepting_new_bookings");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cancellation_policy");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<decimal?>("HourlyRateCad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hourly_rate_cad");

                    b.Property<string>("IcalToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ical_token");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_status");

                    b.Property<decimal?>("ShopMinimumCad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("shop_minimum_cad");

                    b.Property<string>("StripeConnectAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_connect_account_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_experience");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("IcalToken")
                        .IsUnique()
                        .HasDatabaseName("ix_artists_ical_token")
                        .HasFilter("ical_token IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_artists_user_id");

                    b.HasIndex("AcceptingNewBookings", "PaymentStatus")
                        .HasDatabaseName("ix_artists_accepting_new_bookings_payment_status");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Identity.ArtistLeadTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("booking_type");

                    b.Property<int>("MinimumDays")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_days");

                    b.HasKey("Id")
                        .HasName("pk_artist_lead_times");

                    b.HasIndex("ArtistId", "BookingType")
                        .IsUnique()
                        .HasDatabaseName("ix_artist_lead_times_artist_id_booking_type");

                    b.ToTable("artist_lead_times", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Identity.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<int>("PreferredSearchRadiusKm")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_search_radius_km");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_profiles");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_customer_profiles_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_profiles_user_id");

                    b.ToTable("customer_profiles", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("body");

                    b.Property<bool>("IsReportedFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reported_flag");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("IsReportedFlag")
                        .HasDatabaseName("ix_messages_is_reported_flag");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_sender_id");

                    b.HasIndex("ThreadId", "SentAt")
                        .HasDatabaseName("ix_messages_thread_id_sent_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Messaging.MessageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_user_id");

                    b.Property<string>("Resolution")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_admin_id");

                    b.HasKey("Id")
                        .HasName("pk_message_reports");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_reports_message_id");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("ix_message_reports_reported_at");

                    b.HasIndex("ReportedByUserId")
                        .HasDatabaseName("ix_message_reports_reported_by_user_id");

                    b.HasIndex("Resolution")
                        .HasDatabaseName("ix_message_reports_resolution");

                    b.HasIndex("ResolvedByAdminId")
                        .HasDatabaseName("ix_message_reports_resolved_by_admin_id");

                    b.ToTable("message_reports", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Messaging.MessageThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_message_threads");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_message_threads_booking_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_message_threads_status");

                    b.ToTable("message_threads", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Moderation.UserWarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_admin_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_warnings");

                    b.HasIndex("IssuedByAdminId")
                        .HasDatabaseName("ix_user_warnings_issued_by_admin_id");

                    b.HasIndex("UserId", "IssuedAt")
                        .HasDatabaseName("ix_user_warnings_user_id_issued_at");

                    b.ToTable("user_warnings", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Notifications.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_enabled");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("push_enabled");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_preferences");

                    b.HasIndex("UserId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_preferences_user_id_type");

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Notifications.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("endpoint");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("UserId", "Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_subscriptions_user_id_endpoint");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Portfolio.PortfolioPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ApproximateSizeCm")
                        .HasColumnType("integer")
                        .HasColumnName("approximate_size_cm");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("BodyPlacement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("body_placement");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("EstimatedSessionLengthHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_session_length_hours");

                    b.PrimitiveCollection<string[]>("FreeformTags")
                        .IsRequired()
                        .HasColumnType("character varying(50)[]")
                        .HasColumnName("freeform_tags");

                    b.Property<Guid?>("LinkedBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_booking_id");

                    b.Property<string>("ProgressionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("progression_status");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("YearCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("year_completed");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_pieces");

                    b.HasIndex("BodyPlacement")
                        .HasDatabaseName("ix_portfolio_pieces_body_placement");

                    b.HasIndex("LinkedBookingId")
                        .HasDatabaseName("ix_portfolio_pieces_linked_booking_id");

                    b.HasIndex("ArtistId", "CreatedAt")
                        .HasDatabaseName("ix_portfolio_pieces_artist_id_created_at");

                    b.ToTable("portfolio_pieces", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Portfolio.SessionPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HiddenReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hidden_reason");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<DateTime?>("LinkedSessionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_session_date");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("PhotoType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("photo_type");

                    b.Property<Guid>("PortfolioPieceId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_piece_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedByRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("uploaded_by_role");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_session_photos");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_session_photos_uploaded_by_user_id");

                    b.HasIndex("PortfolioPieceId", "Order")
                        .HasDatabaseName("ix_session_photos_portfolio_piece_id_order");

                    b.ToTable("session_photos", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Portfolio.TattooStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCanonical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_canonical");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tattoo_styles");

                    b.HasIndex("IsCanonical")
                        .HasDatabaseName("ix_tattoo_styles_is_canonical");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tattoo_styles_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tattoo_styles_slug");

                    b.ToTable("tattoo_styles", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Stripe.StripeProcessedEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId")
                        .HasName("pk_stripe_processed_events");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_stripe_processed_events_processed_at");

                    b.ToTable("stripe_processed_events", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Studios.ArtistStudioAffiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffiliationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("affiliation_type");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid")
                        .HasColumnName("studio_id");

                    b.HasKey("Id")
                        .HasName("pk_artist_studio_affiliations");

                    b.HasIndex("StudioId", "Status")
                        .HasDatabaseName("ix_artist_studio_affiliations_studio_id_status");

                    b.HasIndex("ArtistId", "IsPrimary", "Status")
                        .HasDatabaseName("ix_artist_studio_affiliations_artist_id_is_primary_status");

                    b.ToTable("artist_studio_affiliations", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Studios.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AcceptsWalkIns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("accepts_walk_ins");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("CreatedByArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_artist_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("JoinPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("join_policy");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("StudioType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("studio_type");

                    b.HasKey("Id")
                        .HasName("pk_studios");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_studios_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_studios_name");

                    b.HasIndex("StudioType")
                        .HasDatabaseName("ix_studios_studio_type");

                    b.ToTable("studios", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Studios.StudioHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("close_time");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("open_time");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid")
                        .HasColumnName("studio_id");

                    b.HasKey("Id")
                        .HasName("pk_studio_hours");

                    b.HasIndex("StudioId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_studio_hours_studio_id_day_of_week");

                    b.ToTable("studio_hours", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Verification.ArtistCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("credential_type");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("document_url");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<Guid>("JurisdictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("jurisdiction_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_admin_id");

                    b.HasKey("Id")
                        .HasName("pk_artist_credentials");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("ix_artist_credentials_expiry_date");

                    b.HasIndex("JurisdictionId")
                        .HasDatabaseName("ix_artist_credentials_jurisdiction_id");

                    b.HasIndex("VerifiedByAdminId")
                        .HasDatabaseName("ix_artist_credentials_verified_by_admin_id");

                    b.HasIndex("ArtistId", "CredentialType", "VerificationStatus")
                        .HasDatabaseName("ix_artist_credentials_artist_id_credential_type_verification_s");

                    b.ToTable("artist_credentials", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Verification.Jurisdiction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<bool>("RequiresArtistHygieneTraining")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_artist_hygiene_training");

                    b.Property<bool>("RequiresArtistLicense")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_artist_license");

                    b.Property<bool>("RequiresBloodbornePathogenCert")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_bloodborne_pathogen_cert");

                    b.Property<bool>("RequiresStudioInspection")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_studio_inspection");

                    b.HasKey("Id")
                        .HasName("pk_jurisdictions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_jurisdictions_name");

                    b.ToTable("jurisdictions", (string)null);
                });

            modelBuilder.Entity("Needlr.Domain.Verification.StudioCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("credential_type");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("document_url");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<Guid>("JurisdictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("jurisdiction_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid")
                        .HasColumnName("studio_id");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_admin_id");

                    b.HasKey("Id")
                        .HasName("pk_studio_credentials");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("ix_studio_credentials_expiry_date");

                    b.HasIndex("JurisdictionId")
                        .HasDatabaseName("ix_studio_credentials_jurisdiction_id");

                    b.HasIndex("VerifiedByAdminId")
                        .HasDatabaseName("ix_studio_credentials_verified_by_admin_id");

                    b.HasIndex("StudioId", "CredentialType", "VerificationStatus")
                        .HasDatabaseName("ix_studio_credentials_studio_id_credential_type_verification_s");

                    b.ToTable("studio_credentials", (string)null);
                });

            modelBuilder.Entity("Needlr.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("SuspensionReason")
                        .HasColumnType("text")
                        .HasColumnName("suspension_reason");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Needlr.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_is_revoked_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("artist_styles", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<Guid>("StylesId")
                        .HasColumnType("uuid")
                        .HasColumnName("styles_id");

                    b.HasKey("ArtistId", "StylesId")
                        .HasName("pk_artist_styles");

                    b.HasIndex("StylesId")
                        .HasDatabaseName("ix_artist_styles_styles_id");

                    b.ToTable("artist_styles", (string)null);
                });

            modelBuilder.Entity("customer_profile_preferred_styles", b =>
                {
                    b.Property<Guid>("CustomerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_profile_id");

                    b.Property<Guid>("PreferredStylesId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_styles_id");

                    b.HasKey("CustomerProfileId", "PreferredStylesId")
                        .HasName("pk_customer_profile_preferred_styles");

                    b.HasIndex("PreferredStylesId")
                        .HasDatabaseName("ix_customer_profile_preferred_styles_preferred_styles_id");

                    b.ToTable("customer_profile_preferred_styles", (string)null);
                });

            modelBuilder.Entity("portfolio_piece_styles", b =>
                {
                    b.Property<Guid>("PortfolioPieceId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_piece_id");

                    b.Property<Guid>("StylesId")
                        .HasColumnType("uuid")
                        .HasColumnName("styles_id");

                    b.HasKey("PortfolioPieceId", "StylesId")
                        .HasName("pk_portfolio_piece_styles");

                    b.HasIndex("StylesId")
                        .HasDatabaseName("ix_portfolio_piece_styles_styles_id");

                    b.ToTable("portfolio_piece_styles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("Needlr.Domain.Availability.ArtistAvailabilityProjection", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_availability_projections_artists_artist_id");
                });

            modelBuilder.Entity("Needlr.Domain.Availability.AvailabilityOverride", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_overrides_artists_artist_id");
                });

            modelBuilder.Entity("Needlr.Domain.Availability.AvailabilityPattern", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_patterns_artists_artist_id");
                });

            modelBuilder.Entity("Needlr.Domain.Availability.BookingWindow", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_windows_artists_artist_id");
                });

            modelBuilder.Entity("Needlr.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_artists_artist_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_customer_id");

                    b.HasOne("Needlr.Domain.Studios.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_studios_studio_id");
                });

            modelBuilder.Entity("Needlr.Domain.Bookings.BookingAttachment", b =>
                {
                    b.HasOne("Needlr.Domain.Bookings.Booking", null)
                        .WithMany("Attachments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_booking_attachments_bookings_booking_id");

                    b.HasOne("Needlr.Domain.Messaging.Message", null)
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_booking_attachments_messages_message_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_attachments_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("Needlr.Domain.Bookings.BookingFeedback", b =>
                {
                    b.HasOne("Needlr.Domain.Bookings.Booking", null)
                        .WithOne("Feedback")
                        .HasForeignKey("Needlr.Domain.Bookings.BookingFeedback", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_feedbacks_bookings_booking_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_feedbacks_users_customer_id");
                });

            modelBuilder.Entity("Needlr.Domain.Identity.Artist", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Needlr.Domain.Identity.Artist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artists_users_user_id");
                });

            modelBuilder.Entity("Needlr.Domain.Identity.ArtistLeadTime", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany("LeadTimes")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_lead_times_artists_artist_id");
                });

            modelBuilder.Entity("Needlr.Domain.Identity.CustomerProfile", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Needlr.Domain.Identity.CustomerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_profiles_users_user_id");
                });

            modelBuilder.Entity("Needlr.Domain.Messaging.Message", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_id");

                    b.HasOne("Needlr.Domain.Messaging.MessageThread", null)
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_message_threads_thread_id");
                });

            modelBuilder.Entity("Needlr.Domain.Messaging.MessageReport", b =>
                {
                    b.HasOne("Needlr.Domain.Messaging.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_reports_messages_message_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_reports_users_reported_by_user_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_message_reports_users_resolved_by_admin_id");
                });

            modelBuilder.Entity("Needlr.Domain.Messaging.MessageThread", b =>
                {
                    b.HasOne("Needlr.Domain.Bookings.Booking", null)
                        .WithOne("MessageThread")
                        .HasForeignKey("Needlr.Domain.Messaging.MessageThread", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_threads_bookings_booking_id");
                });

            modelBuilder.Entity("Needlr.Domain.Moderation.UserWarning", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IssuedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_warnings_users_issued_by_admin_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_warnings_users_user_id");
                });

            modelBuilder.Entity("Needlr.Domain.Notifications.NotificationPreference", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_preferences_users_user_id");
                });

            modelBuilder.Entity("Needlr.Domain.Notifications.PushSubscription", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");
                });

            modelBuilder.Entity("Needlr.Domain.Portfolio.PortfolioPiece", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_pieces_artists_artist_id");

                    b.HasOne("Needlr.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("LinkedBookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_portfolio_pieces_bookings_linked_booking_id");
                });

            modelBuilder.Entity("Needlr.Domain.Portfolio.SessionPhoto", b =>
                {
                    b.HasOne("Needlr.Domain.Portfolio.PortfolioPiece", null)
                        .WithMany("Sessions")
                        .HasForeignKey("PortfolioPieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_photos_portfolio_pieces_portfolio_piece_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_photos_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("Needlr.Domain.Studios.ArtistStudioAffiliation", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany("Affiliations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_studio_affiliations_artists_artist_id");

                    b.HasOne("Needlr.Domain.Studios.Studio", null)
                        .WithMany("Affiliations")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_studio_affiliations_studios_studio_id");
                });

            modelBuilder.Entity("Needlr.Domain.Studios.StudioHours", b =>
                {
                    b.HasOne("Needlr.Domain.Studios.Studio", null)
                        .WithMany("Hours")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studio_hours_studios_studio_id");
                });

            modelBuilder.Entity("Needlr.Domain.Verification.ArtistCredential", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_credentials_artists_artist_id");

                    b.HasOne("Needlr.Domain.Verification.Jurisdiction", null)
                        .WithMany()
                        .HasForeignKey("JurisdictionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_artist_credentials_jurisdictions_jurisdiction_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_artist_credentials_users_verified_by_admin_id");
                });

            modelBuilder.Entity("Needlr.Domain.Verification.StudioCredential", b =>
                {
                    b.HasOne("Needlr.Domain.Verification.Jurisdiction", null)
                        .WithMany()
                        .HasForeignKey("JurisdictionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_studio_credentials_jurisdictions_jurisdiction_id");

                    b.HasOne("Needlr.Domain.Studios.Studio", null)
                        .WithMany("Credentials")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studio_credentials_studios_studio_id");

                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_studio_credentials_users_verified_by_admin_id");
                });

            modelBuilder.Entity("Needlr.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("Needlr.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("artist_styles", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_styles_artists_artist_id");

                    b.HasOne("Needlr.Domain.Portfolio.TattooStyle", null)
                        .WithMany()
                        .HasForeignKey("StylesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_styles_tattoo_styles_styles_id");
                });

            modelBuilder.Entity("customer_profile_preferred_styles", b =>
                {
                    b.HasOne("Needlr.Domain.Identity.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_profile_preferred_styles_customer_profiles_custome");

                    b.HasOne("Needlr.Domain.Portfolio.TattooStyle", null)
                        .WithMany()
                        .HasForeignKey("PreferredStylesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_profile_preferred_styles_tattoo_styles_preferred_s");
                });

            modelBuilder.Entity("portfolio_piece_styles", b =>
                {
                    b.HasOne("Needlr.Domain.Portfolio.PortfolioPiece", null)
                        .WithMany()
                        .HasForeignKey("PortfolioPieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_piece_styles_portfolio_pieces_portfolio_piece_id");

                    b.HasOne("Needlr.Domain.Portfolio.TattooStyle", null)
                        .WithMany()
                        .HasForeignKey("StylesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_piece_styles_tattoo_styles_styles_id");
                });

            modelBuilder.Entity("Needlr.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Feedback");

                    b.Navigation("MessageThread");
                });

            modelBuilder.Entity("Needlr.Domain.Identity.Artist", b =>
                {
                    b.Navigation("Affiliations");

                    b.Navigation("LeadTimes");
                });

            modelBuilder.Entity("Needlr.Domain.Messaging.Message", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Needlr.Domain.Messaging.MessageThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Needlr.Domain.Portfolio.PortfolioPiece", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Needlr.Domain.Studios.Studio", b =>
                {
                    b.Navigation("Affiliations");

                    b.Navigation("Credentials");

                    b.Navigation("Hours");
                });
#pragma warning restore 612, 618
        }
    }
}
